from __future__ import annotations

import re

from sqlglot import exp

# Property subclasses that represent physical/storage characteristics we want to
# ignore by default. Anything on this list is removed from CREATE-level
# `properties` before diffing.
_STORAGE_PROPERTY_TYPES: tuple[type[exp.Expression], ...] = tuple(
    c for c in (
        getattr(exp, "TablespaceProperty", None),
        getattr(exp, "PartitionedByProperty", None),
        getattr(exp, "WithDataProperty", None),
        getattr(exp, "LockingProperty", None),
        getattr(exp, "LogProperty", None),
        getattr(exp, "NoLogProperty", None),
        getattr(exp, "Cache", None),
        getattr(exp, "NoCache", None),
        getattr(exp, "CacheProperty", None),
        getattr(exp, "OnCommitProperty", None),
    )
    if c is not None
)

# Constraint names auto-generated by Oracle; carry no semantic value.
_SYS_CON_NAME = re.compile(r"^SYS_C\d+$", re.IGNORECASE)


def normalize(
    trees: list[exp.Expression],
    *,
    ignore_storage: bool = True,
    ignore_column_order: bool = True,
) -> list[exp.Expression]:
    """Return new trees with structural canonicalization applied.

    - uppercase unquoted identifiers
    - drop comments
    - drop system-generated constraint names
    - fold numeric literals
    - optionally remove storage properties
    - sort table-level constraints (not columns, unless ignore_column_order)
    - optionally sort CREATE TABLE columns alphabetically
    """
    return [
        _normalize_one(t, ignore_storage=ignore_storage, ignore_column_order=ignore_column_order)
        for t in trees
    ]


def _normalize_one(
    tree: exp.Expression,
    *,
    ignore_storage: bool,
    ignore_column_order: bool,
) -> exp.Expression:
    tree = tree.copy()
    tree = _drop_comments(tree)
    tree = _uppercase_identifiers(tree)
    tree = _drop_sys_constraint_names(tree)
    tree = _fold_numeric_literals(tree)
    if ignore_storage:
        tree = _drop_storage_properties(tree)
    tree = _sort_table_constraints(tree, sort_columns=ignore_column_order)
    return tree


def _drop_comments(tree: exp.Expression) -> exp.Expression:
    for node in tree.walk():
        n = node[0] if isinstance(node, tuple) else node
        if getattr(n, "comments", None):
            n.comments = None
    return tree


def _uppercase_identifiers(tree: exp.Expression) -> exp.Expression:
    def _t(node: exp.Expression) -> exp.Expression:
        if isinstance(node, exp.Identifier) and not node.args.get("quoted"):
            if isinstance(node.this, str):
                node.set("this", node.this.upper())
        return node

    return tree.transform(_t, copy=False)


def _drop_sys_constraint_names(tree: exp.Expression) -> exp.Expression:
    def _t(node: exp.Expression) -> exp.Expression:
        if isinstance(node, exp.Constraint):
            name = node.args.get("this")
            # Constraint.this is an Identifier (wrapper); probe its `.name`.
            raw = getattr(name, "name", None) or (name if isinstance(name, str) else None)
            if raw and _SYS_CON_NAME.match(raw):
                node.set("this", None)
        return node

    return tree.transform(_t, copy=False)


def _fold_numeric_literals(tree: exp.Expression) -> exp.Expression:
    def _t(node: exp.Expression) -> exp.Expression:
        if isinstance(node, exp.Literal) and node.is_number:
            raw = node.this
            try:
                as_float = float(raw)
            except (TypeError, ValueError):
                return node
            canonical = (
                str(int(as_float))
                if as_float.is_integer() and "." not in raw.lstrip("-+").split("e")[0].split("E")[0]
                or (as_float.is_integer() and ("e" in raw.lower()))
                else raw
            )
            if canonical != raw:
                node.set("this", canonical)
        return node

    return tree.transform(_t, copy=False)


def _drop_storage_properties(tree: exp.Expression) -> exp.Expression:
    if not _STORAGE_PROPERTY_TYPES:
        return tree

    def _t(node: exp.Expression) -> exp.Expression:
        if isinstance(node, exp.Properties):
            keep = [p for p in node.expressions if not isinstance(p, _STORAGE_PROPERTY_TYPES)]
            node.set("expressions", keep)
        return node

    tree = tree.transform(_t, copy=False)

    # If a CREATE's properties arg is now empty, drop it entirely.
    props = tree.args.get("properties") if isinstance(tree, exp.Create) else None
    if isinstance(props, exp.Properties) and not props.expressions:
        tree.set("properties", None)
    return tree


def _sort_table_constraints(
    tree: exp.Expression, *, sort_columns: bool
) -> exp.Expression:
    """In CREATE TABLE ... (col1, col2, CONSTRAINT ..., CONSTRAINT ...),
    sort the trailing table-level constraints alphabetically by their rendered
    form. Column definitions are sorted too when `sort_columns` is true.
    """
    def _t(node: exp.Expression) -> exp.Expression:
        if not isinstance(node, exp.Schema):
            return node
        exprs = list(node.expressions or [])
        if not exprs:
            return node
        columns: list[exp.Expression] = []
        constraints: list[exp.Expression] = []
        for e in exprs:
            if isinstance(e, exp.ColumnDef):
                columns.append(e)
            else:
                constraints.append(e)
        if sort_columns:
            columns.sort(key=lambda c: c.sql(dialect="oracle"))
        if constraints:
            constraints.sort(key=lambda c: c.sql(dialect="oracle"))
        if sort_columns or constraints:
            node.set("expressions", columns + constraints)
        return node

    return tree.transform(_t, copy=False)


def render(trees: list[exp.Expression]) -> str:
    """Render a normalized tree list back to canonical Oracle SQL for text diffs."""
    chunks = [t.sql(dialect="oracle", pretty=True) for t in trees]
    return ";\n".join(chunks).rstrip() + ";\n"
